# Generated by Django 3.2.5 on 2021-07-13 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='cli_id', primary_key=True, serialize=False)),
                ('cedula', models.CharField(db_column='cli_cedula', max_length=20)),
                ('nombre', models.CharField(db_column='cli_nombre', max_length=250)),
                ('apellido', models.CharField(db_column='cli_apellido', max_length=250)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(db_column='tra_id', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='tra_fecha')),
                ('valor', models.FloatField(db_column='tra_valor')),
                ('saldo_anterior', models.FloatField(db_column='tra_saldo_anterior')),
                ('saldo_actual', models.FloatField(db_column='tra_saldo_actual')),
                ('cliente', models.ForeignKey(db_column='tra_cli_id', on_delete=django.db.models.deletion.CASCADE, to='transacciones.cliente')),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
            },
        ),
    ]
