# Generated by Django 3.2.5 on 2021-07-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(db_column='tra_tipo', default='Deposito', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(db_column='cli_cedula', max_length=20, unique=True),
        ),
    ]
